-- Create "file_storages" table
CREATE TABLE "file_storages" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "bucket_name" character varying NOT NULL, "object_key" character varying NOT NULL, "original_file_name" character varying NULL, "file_size" bigint NULL, "content_type" character varying NULL, "file_hash" character varying NULL, PRIMARY KEY ("id"));
-- Create index "filestorage_bucket_name_object_key" to table: "file_storages"
CREATE INDEX "filestorage_bucket_name_object_key" ON "file_storages" ("bucket_name", "object_key");
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "verified" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create "password_tokens" table
CREATE TABLE "password_tokens" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "hash" character varying NOT NULL, "created_at" timestamptz NOT NULL, "password_token_user" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "password_tokens_users_user" FOREIGN KEY ("password_token_user") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
